---

- name: RedHat | install current/latest network packages versions
  yum:
    name: '{{ item }}'
    state: '{{ interfaces_pkg_state }}'
  with_items: '{{ interfaces_pkgs["redhat"] }}'
  tags: package
