---
- name: RedHat | install current/latest network packages versions
  become: true
  package:
    name: '{{  interfaces_pkgs["redhat"][ansible_distribution_major_version] }}'
    state: '{{ interfaces_pkg_state }}'
  tags: package

- name: RedHat | ensure network service is started and enabled
  become: true
  service:
    name: network
    enabled: true
    state: started
